### ISSUE TITLE
Cannot install through composer.

### ISSUE THREAD

**Issue by 9brada6** [llaville/graph-uml#2]
Hi, I try to install your package through composer, but I get the following error:
 composer require bartlett/graph-uml
Using version dev-master for bartlett/graph-uml
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for bartlett/graph-uml dev-master -> satisfiable by bartlett/graph-uml[dev-master].
>     - bartlett/graph-uml dev-master requires graphp/graphviz dev-subgraph_cluster_attributes as 1.0.0 -> no matching package found.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
>  - It's a private package and you forgot to add a custom repository to find it
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
> 
> Installation failed, reverting ./composer.json to its original content.

I have minimum-stability: dev in in composer.json, but the package is also not found... I remember triyng to install your package some months ago, an I think I did it, but I forgot how... Is there something that I can do? Using google search I cannot any package...
https://www.google.com/search?q=dev-subgraph_cluster_attributes&oq=dev-subgraph_cluster_attributes&aqs=chrome.0.69i59.336j0j4&sourceid=chrome&ie=UTF-8

**Comment by 9brada6** [comment]
I figured out eventually: I needed to add this in my requirements package: "graphp/graphviz": "dev-master@dev as dev-subgraph_cluster_attributes". But I also wanted to install the plantUML and get lost between packages... I will let this issue open, because I think that maybe you should write in the documentation a hint that there is a higher level package that people should use(umlwriter), sometimes when searching on internet for things like "PHP UML Generator" or "PHP plantUML Generator"(something like that, don't know exactly), will redirect here, and usually someone would want the other package... Thanks for this program.

**Comment by llaville** [comment]
Main reason, and quick answer may be found at https://github.com/llaville/umlwriter/issues/14#issuecomment-681716402
But a more stable solution should be provide, I know and I agree

**Comment by llaville** [comment]
Version 1.0.0-rc.3 released yesterday may now be installed via composer. I've removed usage of `graph/graphviz` fork and replaced by usage of vendor patches.
See https://github.com/cweagans/composer-patches, and read good introduction article at https://tomasvotruba.com/blog/2020/07/02/how-to-patch-package-in-vendor-yet-allow-its-updates/

Final stable version 1.0.0 will come shortly now !
